ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: 9/m3eWQ-7c9a5XZHW?bc5yTzLr?iIR7cv2llbRfbAWe-hg0zVGTsT=ZKW0Bt0HV6dFN1AOuTb7DtPplvAvE/g4f-rKejht?Rks3qCVl8iw2LvYtCCUkL-auHRehFIoRZAcXdB6oC0z6Nom9oMzSnXlSAhJEmMFzPZ1bC7BcT0f?E2My=LEk1QwcsCx29NflYcaS2lM810sWxELX32KkZAbVPkqiwCTm?EELAqclFajns5CGQq2chgwQiUUrT3sglpPKEIq/alR=nIN0yGNRr01Fe1l=N=4AivnTRdNaM254?WXW02MUf28MTlFLuPChuKk7mR2Szr?iasMcFCKJnI-rAPTp?a3=Mv1GRARPiqAMV6Nl?//Q?YbxjPJlKBN4tou0GgDTEN9rBM97qSVi?/B3hpNiB2uI?B9Vu2jrNjwEDLTrepSyhqoSMp0yZnmjMsBkh2ZhohMDZUvCGcxR5odf5uTH9kHmWO7ao!=2VHoYfPoX0CORg3kFdc=I!Zk/O
    jwtExpirationMs: 14400000

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost