server:
  port: 8086
  servlet:
    context-path: '/ead-payment/'
spring:
  application:
    name: ead-payment-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-payment
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://ruefzhwe:E7VAZe3q29on7h26eTbNdYZHeT4aqLfw@chimpanzee.rmq.cloudamqp.com/ruefzhwe
    
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health