server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'
spring:
  application:
    name: ead-authuser-service
  datasource:
    url:  ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://ruefzhwe:E7VAZe3q29on7h26eTbNdYZHeT4aqLfw@chimpanzee.rmq.cloudamqp.com/ruefzhwe
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent
authuser:
  refreshscope:
    name: jefferson barbosa update
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80

  retry:
    instances:
      retryInstance:
        maxAttempts: 3
        waitDuration: 5s